---
  - name: Helath checking
    hosts: test
    gather_facts: no

    vars:
      ETCPASSWD: /etc/passwd
      ETCGROUP: /etc/group
      ansible_python_interpreter: /usr/bin/python
      LOGKEEPER: /usr/local/bin

# Users
    tasks:
    - name: Duplicated user
      shell:
        cmd: |
          awk -F : '{print ":"$3":"}'  {{ ETCPASSWD }} | sort | uniq -d | xargs -I {} grep {} {{ ETCPASSWD }} | cut -f1 -d: | sort -u
      register: awk_result_user

    - debug: msg="Duplicated user(s)':' {{awk_result_user.stdout}}"
      when: awk_result_user.stdout != ""

# Groups
    - name: Duplicated groups
      shell:
        cmd: |
          awk -F : '{print ":"$3":"}' {{ ETCGROUP }} | sort | uniq -d | xargs -I {} grep {} {{ ETCGROUP }} | cut -f1 -d: | sort -u
      register: awk_result_group

    - debug: msg="Duplicated users {{awk_result_group.stdout}}"
      when: awk_result_group.stdout != ""

# N/A : activity_audit_req_1 ctivity_audit_req_2

# activity_audit_req_3 (Logkeeper)
    - name: Log retention days must be 90
      find:
        paths: /usr/local/bin
        patterns: logkeeper.cfg
        contains: "^[$]trim_retention_days+( )=+( )90( *);"
        use_regex: yes
      register: logkeeper_result

    - debug: msg="Log retention is NOT 90 days !"
      when:  logkeeper_result.matched  != 1


# Def maxage
    - name: Default maxage
      shell: lssec -f /etc/security/user -s default -a maxage
      register: lssec_result

    - debug: 
        msg: "{{ lssec_result.stdout }}"














      