---
- hosts: all
  tasks:
  - include_role:
      name: check_username_LZ
    when: "ansible_facts['os_family'] == 'RedHat'"
#  - include_role:
#      name: check_username_UX
#    when: "ansible_facts['os_family'] == 'AIX'"
...
